# Generated by Django 5.2.4 on 2025-07-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.CharField(
                        help_text="The full text of the question to be displayed to the user.",
                        max_length=300,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="BodyPartQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_part",
                    models.CharField(
                        help_text="The name of the body part (e.g., 'torso-lower', 'pelvis'). Must match the SVG ID.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        help_text="Select the set of questions relevant to this body part.",
                        to="app.question",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Body Part Question Sets",
            },
        ),
    ]
