# Generated by Django 5.2.4 on 2025-07-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="feature_name",
            field=models.CharField(
                default=0,
                help_text="The corresponding short feature name for the model (e.g., 'headache', 'back_pain').",
                max_length=100,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
